### ISSUE TITLE
Keybinding problem with fuzzy-finder:toggle-file-finder (ctrl-p)

### ISSUE THREAD

**Issue by alextselegidis** [alairock/phpunit-atom#37]
First of all thank you very much for your plugin, good job. 

I experienced an issue with my Atom installation on a Linux Ubuntu 14.04 machine, where whenever I pressed the CTRL + P keystroke the file finder popup would not open. Then I checked the keybindings and saw that by default phpunit-atom had the following key binding `ctrl-p x` which resolves to the `phpunit:destroy` command.

I am not sure if the problem occurs only to me, but if you can reproduce it, it might be better to change this keybinding. 

Best Regards, 

Alex

**Comment by alextselegidis** [comment]
PS: The problem solved after disabling your package.

**Comment by melanholly** [comment]
I have disabled this issue after disabling only the keyboard shortcut in the package settings. You can use the package well after that.
